# -*- coding: utf-8 -*-
"""DescriptiveData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rlteSqftUVy4PH8-dCf1RFqgNTQNWC8Y
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# Sample student marks dataset
data = {
    'Student': ['A','B','C','D','E'],
    'Marks': [75, 80, 85, 90, 95]
}
# Create DataFrame
df = pd.DataFrame(data)
print(df)
# Sample student marks dataset
data = {
    'Student': ['A','B','C','D','E'],
    'Marks': [75, 80, 85, 90, 95]
}
# Create DataFrame
df = pd.DataFrame(data)
print(df)
# Mean
mean_value = df['Marks'].mean()
# Median
median_value = df['Marks'].median()
# Mode
mode_value = df['Marks'].mode()[0]
# Standard Deviation
std_value = df['Marks'].std()
# Display results
print("Mean:", mean_value)
print("Median:", median_value)
print("Mode:", mode_value)
print("Standard Deviation:", std_value)
print(df.describe())
plt.figure(figsize=(7,5))
plt.bar(df['Student'],
        df['Marks'],
        color='blue')
plt.title("Student Marks Analysis")
plt.xlabel("Students")
plt.ylabel("Marks")
plt.show()
plt.figure(figsize=(7,5))
plt.hist(df['Marks'],
         bins=5,
         color='green')
plt.title("Marks Distribution")
plt.xlabel("Marks")
plt.ylabel("Frequency")
plt.show()